### ISSUE TITLE
Check if the class \Essence\Essence exists before requiring

### ISSUE THREAD

**Issue by romaincazier** [neuerituale/FieldtypeOembed#3]
Hi,

I think it'd be best to check for the existence of the class \Essence\Essence before calling [`require_once`](https://github.com/neuerituale/FieldtypeOembed/blob/64cf553cc45eeb51d72afaad09452057b298e053/FieldtypeOembed.module#L205) as one might have a different composer setup (I have a similar one to what’s described [here](https://processwire.dev/integrate-composer-with-processwire/#recommended-directory-structure-for-processwire-projects-with-composer)).

```php
// ...
if(!class_exists("\Essence\Essence")) {
	if(!file_exists(__DIR__ . '/vendor/autoload.php')) {
		throw new \Exception('Please install essence in your the module directory.');
	}
	require_once(/*NoCompile*/__DIR__ . '/vendor/autoload.php');
}
// ...
```

Thanks

**Comment by julianwinkel** [comment]
Thank you for your help. I have implemented the class check. 
The module is now also accessible via Composer
