### ISSUE TITLE
`Warning: array_key_exists` when installing module

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [neuerituale/FieldtypeOembed#4]
When installing the module and refreshing the module cache, the following error shows up (2-3 times) at the top of the module page (with debug mode on):
`Warning: array_key_exists(): The first argument should be either a string or an integer in /wire/core/WireData.php on line 172`

After removing the module, the error is gone again.

Module version 1.1.4
ProcessWire 3.0.210
PHP 7.4

**Comment by julianwinkel** [comment]
I can't figure it out at the moment, but the error appears when a module that is not installed is listed in `required` in the module GraphQLFieldtypeOembed. 
The workaround is not to list this module (ProcessGraphQL)
