### ISSUE TITLE
Uncaught TypeError on refreshOembed data

### ISSUE THREAD

**Issue by solonmedia** [neuerituale/FieldtypeOembed#6]
When the module updates oembed data via the cron job, I get an error message that appears in the admin:

Uncaught TypeError: FieldtypeOembed::getMatchQuery(): Return value must be of type PageFinderDatabaseQuerySelect, DatabaseQuerySelect returned in site-base/modules/FieldtypeOembed/FieldtypeOembed.module:322

I'm not sure if this is related to changes made on the PW side recently, but I thought I'd let you know about the issue.

Currently running v 1.1.5 of the module on v 3.0.220 of processwire.

**Comment by solonmedia** [comment]
Looking into it further, the modules extends FieldtypeURL which inherits its getMatchQuery from FieldtypeText which returns DatabaseQuerySelect as a type.

Setting the function restriction in line 280:

`public function getMatchQuery($query, $table, $subfield, $operator, $value): DatabaseQuerySelect {`

seems to resolve the issue.

**Comment by julianwinkel** [comment]
@solonmedia Thanks for your contribution, I have removed the return type declaration from `getMatchQuery`.
